export { FetchError } from './FetchError'
export { fetchDocument } from './fetchDocument'
export { fetchJSON } from './fetchJSON'
export { fetchText } from './fetchText'
export { yahooFetch } from './yahooFetch'
